syntax on
set relativenumber
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim


call vundle#begin()
Plugin 'easymotion/vim-easymotion'
Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
call vundle#end()

let g:airline_powerline_fonts = 1

set wildmenu

set guifont=DejaVu\ Sans\ Mono\ 11
language en_US.utf8
filetype plugin indent on

set laststatus=2
let mapleader=","


" EasyMotion
let g:EasyMotion_smartcase = 1

map  <Leader>f <Plug>(easymotion-bd-f)
map  <Leader>w <Plug>(easymotion-bd-w)

nnoremap <Leader>wq :wq<CR>
nnoremap <Leader>qq :q!<CR>
