syntax on
set relativenumber
set number
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim


call vundle#begin()
Plugin 'easymotion/vim-easymotion'
Plugin 'ctrlpvim/ctrlp.vim'
call vundle#end()

let g:airline_powerline_fonts = 1

set wildmenu

set guifont=DejaVu\ Sans\ Mono\ 11
language en_US.utf8
filetype plugin indent on

set laststatus=2
let mapleader=","

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" EasyMotion
let g:EasyMotion_smartcase = 1

map  <Leader>f <Plug>(easymotion-bd-f)
map  <Leader>w <Plug>(easymotion-bd-w)

nnoremap <Leader>wq :wq<CR>
nnoremap <Leader>qq :q!<CR>
