execute pathogen#infect()
syntax on
filetype plugin indent on
set relativenumber
set laststatus=2

let g:airline_powerline_fonts = 1
set guifont=Ubuntu\ Mono\ derivative\ Powerline\ Regular:h14

set wildmenu

let g:airline_theme='wombat'


set guifont=DejaVu\ Sans\ Mono\ 11
language en_US.utf8
